### ISSUE TITLE
Please style the login

### ISSUE THREAD

**Issue by chriswirz** [henrykapostel/whereyouat#2]
Great!  It looks like you have a good grasp of integrating the API/SDK.  Part of what we are looking for is how much of an aesthetic eye you have.  Please style the LoginViewController to look "cool".  A little manipulation of dependency properties goes a long way.

**Comment by henrykapostel** [comment]
I just committed with updated the UI of Login View.
Please check it out and let me know if you still have got any problems.

**Comment by chriswirz** [comment]
Looks great!
