### ISSUE TITLE
Comment your code

### ISSUE THREAD

**Issue by chriswirz** [henrykapostel/whereyouat#3]
I want to see more original comments from you.  Make it seem like you are working with a team that will have to continue using your code for the next 5 years.  Part of what we are looking for is maintainability.  I know, I know, this is a simple exercise with very self-explanatory code, so what is the point, but this is something former team members didn't do, and it is causing us some headache. 

you can remove my comments such as this:
//
// this is where the front-end magic happens
//
// commands such as println("user=\(user)") will help see what is going on
//
// below is the 100% safest way to handle the optional parameters

**Comment by henrykapostel** [comment]
I just did some comments on login and public controller.
Please check it out

**Comment by chriswirz** [comment]
I guess it's good enough for this demo.  XCode really doesn't do much to promote comments and documentation.  In the real development environment, just make sure to comment more often.
